### ISSUE TITLE
Solucion-lab12 

### ISSUE THREAD

**Issue by Jerimy2021** [cs1000-utec/solucion-labs#1]
Deseo agregar los pasos de solución del laboratorio número 12, es decir, realizar con imágenes el procedimiento que nos indico y describir el procedimiento del lab.
Motivo: Un punto extra en la PC1.

**Comment by franciscovilchezv** [comment]
Proceder. Probablemente hagas observaciones en el PR ya que no estoy seguro de los cambios que hará
