### ISSUE TITLE
Solución lab11

### ISSUE THREAD

**Issue by RodrigoSebasT** [cs1000-utec/solucion-labs#4]
Usando el motor gráfico de python, Ursina. He dibujado mis iniciales para recuperar el lab 11. Le dejo mi solución con todo lo pedido en el lab.

Nombre Rodrigo Sebastian Trujillo MIrano.
Curso: ICC laboratorio 1.02.
Horario: Jueves de 9:00 a 11:00 am

[lab11.zip](https://github.com/cs1000-utec/solucion-labs/files/7739619/lab11.zip)

**Comment by franciscovilchezv** [comment]
Proceder con el PR
